# Dependencies
markdown:         kramdown
#highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true #for the 2.x to 3.x update, which changed permalinks

# Setup
title:            Rudi's site
tagline:          ''
description:      ''
url:              https://rm646.github.io/blag
baseurl:          /blag

author:
  name:           'Rudi Mears'

paginate:         5

collections:
  lists:
    output: true

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rm646/blag
