# Dependencies
markdown:         kramdown
#highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true #for the 2.x to 3.x update, which changed permalinks

# Setup
title:            Blag
tagline:          'Test site'
description:      'A blog and collection of lists.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Ethel Buggine'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rm646/blag
